resources:
  - name: generics
    type: git
    icon: github
    source:
      uri: https://github.com/redislabs-training/generics
      branch: main
      username: ((auth-github))
      password: x-oauth-basic
  - name: hashicorp-poetry-container
    type: registry-image
    icon: docker
    source:
      repository: technicalenablement/generic-hashicorp-poetry
      username: timeartist
      password: ((auth-docker))
  - name: gcloud-poetry-container
    type: registry-image
    icon: docker
    source:
      repository: technicalenablement/generic-gcloud-poetry
      username: timeartist
      password: ((auth-docker))
  - name: poetry-container
    type: registry-image
    icon: docker
    source:
      repository: technicalenablement/generic-poetry
      username: timeartist
      password: ((auth-docker))
  - name: every-monday
    type: time
    source:
      days: [Monday]
jobs: 
  - name: build-hashicorp-poetry-container
    plan:
      - get: generics
      - get: every-monday
        trigger: true
      - task: build
        privileged: true
        file: generics/ci/build-hashicorp-poetry.yml
      - put: hashicorp-poetry-container
        params:
          image: image/image.tar
          version: 0.1.0
          bump_aliases: true
  - name: build-gcloud-poetry-container
    plan:
      - get: generics
      - get: every-monday
        trigger: true
      - task: build
        privileged: true
        file: generics/ci/build-gcloud-poetry.yml
      - put: gcloud-poetry-container
        params:
          image: image/image.tar
          version: 0.1.0
          bump_aliases: true
  - name: build-poetry-container
    plan:
      - get: generics
      - get: every-monday
        trigger: true
      - task: build
        privileged: true
        file: generics/ci/build-poetry.yml
      - put: poetry-container
        params:
          image: image/image.tar
          version: 0.1.0
          bump_aliases: true